"use client";

import { useCallback } from "react";

/**
 * Downloads a raw code string as a local file in the user's browser.
 */
export function exportFile(
  code: string,
  filename = "Component.tsx",
  mimeType = "text/plain;charset=utf-8"
): void {
  if (typeof window === "undefined") return;

  const blob = new Blob([code], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

/**
 * Packages React/HTML component into a standalone, portable HTML file that runs anywhere.
 */
export function exportStandaloneHtml(
  code: string,
  language = "typescript",
  filename = "raizen-preview.html"
): void {
  if (typeof window === "undefined") return;

  const isReact =
    ["react", "tsx", "jsx", "typescript", "ts", "javascript", "js"].includes(
      language.toLowerCase()
    ) ||
    code.includes("import React") ||
    code.includes("<") ||
    code.includes("export default function");

  let processedCode = code;
  if (isReact) {
    processedCode = processedCode
      .replace(/import\s+[\s\S]*?from\s+['"][^'"]+['"];?/g, "")
      .replace(/export\s+default\s+function\s+(\w+)/g, "function $1")
      .replace(/export\s+function\s+(\w+)/g, "function $1")
      .replace(/export\s+default\s+(\w+);?/g, "window.__RAIZEN_ROOT_COMPONENT__ = $1;")
      .replace(/export\s+default\s+/g, "window.__RAIZEN_ROOT_COMPONENT__ = ");

    if (!processedCode.includes("window.__RAIZEN_ROOT_COMPONENT__")) {
      const funcMatches = Array.from(
        processedCode.matchAll(/function\s+([A-Z]\w+)/g)
      );
      if (funcMatches.length > 0) {
        const lastFunc = funcMatches[funcMatches.length - 1][1];
        processedCode += `\nwindow.__RAIZEN_ROOT_COMPONENT__ = ${lastFunc};`;
      }
    }
  }

  const standaloneHtml = `<!DOCTYPE html>
<!--
  Generated by RAIZEN Studio - Enterprise AI Coding Intelligence
  Creator: SHAWAZ (https://shawaz.vercel.app/)
  Model: shawaz03/RAIZEN (7.61B Qwen2.5-Coder base)
-->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>RAIZEN Exported Component</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <script src="https://unpkg.com/lucide@latest"></script>
  <style>
    * { box-sizing: border-box; }
    body {
      margin: 0;
      padding: 24px;
      background-color: #050505;
      color: #E5E5E5;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    }
  </style>
</head>
<body>
  <div id="root"></div>

  ${
    isReact
      ? `
      <script type="text/babel" data-presets="react,typescript">
        const { useState, useEffect, useRef, useMemo, useCallback } = React;
        const LucideIcons = window.lucide || {};

        ${processedCode}

        const Target = window.__RAIZEN_ROOT_COMPONENT__;
        if (Target) {
          const root = ReactDOM.createRoot(document.getElementById('root'));
          root.render(React.createElement(Target));
        }
      </script>
      `
      : `
      <div>${code}</div>
      `
  }
</body>
</html>`;

  exportFile(standaloneHtml, filename, "text/html;charset=utf-8");
}

export function useCodeExport() {
  const downloadCode = useCallback((code: string, filename: string) => {
    exportFile(code, filename);
  }, []);

  const downloadHtml = useCallback((code: string, language: string, filename?: string) => {
    exportStandaloneHtml(code, language, filename);
  }, []);

  return {
    downloadCode,
    downloadHtml,
  };
}
