"use client";

import { useCallback } from "react";

/**
 * Downloads a raw code string as a local file in the user's browser.
 */
export function exportFile(
  code: string,
  filename = "Component.tsx",
  mimeType = "text/plain;charset=utf-8"
): void {
  if (typeof window === "undefined") return;

  const blob = new Blob([code], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

/**
 * Packages React/HTML component into a standalone, portable HTML file that runs anywhere.
 */
export function exportStandaloneHtml(
  code: string,
  language = "typescript",
  filename = "raizen-preview.html"
): void {
  if (typeof window === "undefined") return;

  const isReact =
    ["react", "tsx", "jsx", "typescript", "ts", "javascript", "js"].includes(
      language.toLowerCase()
    ) ||
    code.includes("import React") ||
    code.includes("<") ||
    code.includes("export default function") ||
    code.includes("function ");

  let cleanSource = code;
  if (isReact) {
    cleanSource = cleanSource.replace(/import\s+[\s\S]*?from\s+['"][^'"]+['"];?/g, "");
    cleanSource = cleanSource.replace(/export\s+default\s+function\s+([A-Za-z0-9_]+)/g, "function $1");
    cleanSource = cleanSource.replace(/export\s+function\s+([A-Za-z0-9_]+)/g, "function $1");
    cleanSource = cleanSource.replace(/export\s+default\s+([A-Za-z0-9_]+);?/g, "window.__RAIZEN_ROOT_COMPONENT__ = $1;");
    cleanSource = cleanSource.replace(/export\s+default\s+/g, "window.__RAIZEN_ROOT_COMPONENT__ = ");
    cleanSource = cleanSource.replace(/export\s*\{[^}]*\};?/g, "");

    const allFunctions = Array.from(cleanSource.matchAll(/function\s+([A-Z][A-Za-z0-9_]*)/g)).map(m => m[1]);
    let rootName = null;
    if (allFunctions.includes("App")) {
      rootName = "App";
    } else if (allFunctions.includes("LandingPage")) {
      rootName = "LandingPage";
    } else if (allFunctions.includes("Main")) {
      rootName = "Main";
    } else if (allFunctions.includes("Page")) {
      rootName = "Page";
    } else if (allFunctions.includes("Dashboard")) {
      rootName = "Dashboard";
    } else if (allFunctions.length > 0) {
      rootName = allFunctions[allFunctions.length - 1];
    }

    if (rootName) {
      cleanSource += `\nwindow.__RAIZEN_ROOT_COMPONENT__ = ${rootName};`;
    }
  }

  const encodedSource = JSON.stringify(cleanSource);

  const standaloneHtml = `<!DOCTYPE html>
<!--
  Generated by RAIZEN Studio - Enterprise AI Coding Intelligence
  Creator: SHAWAZ (https://shawaz.vercel.app/)
  Model: shawaz03/RAIZEN (7.61B Qwen2.5-Coder base)
-->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>RAIZEN Exported Component</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <script src="https://unpkg.com/lucide@latest"></script>
  <script>
    function toPascalCase(str) {
      return str.replace(/(^\\w|-\\w)/g, function(c) { return c.replace('-', '').toUpperCase(); });
    }
    function createLucideReactComponent(iconName, iconDef) {
      return function IconComponent(props) {
        var p = props || {};
        var size = p.size || p.width || 20;
        var strokeWidth = p.strokeWidth || 2;
        var className = p.className || '';
        var color = p.color || 'currentColor';
        var inner = '';
        if (Array.isArray(iconDef)) {
          inner = iconDef.map(function(item) {
            var tag = item[0];
            var attrs = item[1];
            var attrStr = Object.keys(attrs).map(function(k) { return k + '="' + attrs[k] + '"'; }).join(' ');
            return '<' + tag + ' ' + attrStr + '></' + tag + '>';
          }).join('');
        }
        return React.createElement('svg', {
          xmlns: 'http://www.w3.org/2000/svg',
          width: size,
          height: size,
          viewBox: '0 0 24 24',
          fill: 'none',
          stroke: color,
          strokeWidth: strokeWidth,
          strokeLinecap: 'round',
          strokeLinejoin: 'round',
          className: className,
          dangerouslySetInnerHTML: { __html: inner }
        });
      };
    }
    window.__initLucideIcons = function() {
      var lucideObj = window.lucide || {};
      var icons = lucideObj.icons || {};
      Object.keys(icons).forEach(function(key) {
        var pascal = toPascalCase(key);
        var comp = createLucideReactComponent(key, icons[key]);
        window[pascal] = comp;
        window[key] = comp;
      });
      var fallbackIcon = function FallbackIcon(props) {
        return React.createElement('span', { className: (props && props.className) || 'inline-block text-signal font-mono' }, '✦');
      };
      [
        'Sparkles', 'Check', 'ArrowRight', 'ArrowLeft', 'ShieldCheck', 'Zap', 'Code', 'Eye',
        'Copy', 'RotateCcw', 'Maximize2', 'Minimize2', 'FileCode', 'Download', 'MessageSquare',
        'Columns', 'Code2', 'Cpu', 'Terminal', 'Play', 'Pause', 'Trash', 'Settings', 'Search',
        'Menu', 'X', 'ExternalLink', 'Github', 'ChevronRight', 'ChevronDown', 'Star', 'User',
        'ShoppingCart', 'Heart', 'Package', 'CreditCard', 'Activity', 'Sliders', 'Layers'
      ].forEach(function(name) {
        if (!window[name]) {
          var lowerKey = name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
          if (icons[lowerKey]) {
            window[name] = createLucideReactComponent(lowerKey, icons[lowerKey]);
          } else {
            window[name] = fallbackIcon;
          }
        }
      });
    };
  </script>
  <style>
    * { box-sizing: border-box; }
    body {
      margin: 0;
      padding: 16px;
      background-color: #050505;
      color: #E5E5E5;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    }
  </style>
</head>
<body>
  <div id="root"></div>

  ${
    isReact
      ? `
      <script>
        (function() {
          try {
            window.__initLucideIcons();
            var rawSource = ${encodedSource};
            var compiled = Babel.transform(rawSource, {
              presets: ['react', 'typescript'],
              filename: 'component.tsx'
            }).code;

            var executeFn = new Function(
              'React', 'ReactDOM', 'useState', 'useEffect', 'useRef', 'useMemo', 'useCallback',
              compiled
            );

            executeFn(
              React, ReactDOM,
              React.useState, React.useEffect, React.useRef, React.useMemo, React.useCallback
            );

            var TargetComponent = window.__RAIZEN_ROOT_COMPONENT__;
            if (TargetComponent) {
              var root = ReactDOM.createRoot(document.getElementById('root'));
              root.render(React.createElement(TargetComponent));
            }
          } catch (err) {
            document.getElementById('root').innerHTML = '<div style="padding: 16px; font-family: monospace; color: #FF6666; background: #150505; border: 1px solid #FF3333;"><h4 style="margin: 0 0 8px 0; color: #FF3333;">[EXECUTION ERROR]</h4><pre style="margin: 0; white-space: pre-wrap; font-size: 11px;">' + (err.message || String(err)) + '</pre></div>';
          }
        })();
      </script>
      `
      : `
      <div>${code}</div>
      `
  }
</body>
</html>`;

  exportFile(standaloneHtml, filename, "text/html;charset=utf-8");
}

export function useCodeExport() {
  const downloadCode = useCallback((code: string, filename: string) => {
    exportFile(code, filename);
  }, []);

  const downloadHtml = useCallback((code: string, language: string, filename?: string) => {
    exportStandaloneHtml(code, language, filename);
  }, []);

  return {
    downloadCode,
    downloadHtml,
  };
}
